//
// Created by Ignacio on 9/22/2024.
//

#ifndef MCBC6_ERRORCODES_H
#define MCBC6_ERRORCODES_H

#define v1_12_2_ERR_SENT_COMP_TO_UNCOMP_HANDLER -3500
#define v1_12_2_ERR_SENT_UNCOMP_TO_COMP_HANDLER -3600

#define ERR_FINDBLOCK_AT_UNLOADED_CHUNK -5100
#define ERR_FINDBLOCK_HEIGHT_BEYOND_CHUNKHEIGHT -5200

#define ZLIB_ERROR_PREFIX -1000
#endif //MCBC6_ERRORCODES_H
